### ISSUE TITLE
Documentation: validatePrivateKey does not check typed array length

### ISSUE THREAD

**Issue by webmaster128** [bitauth/bitcoin-ts#4]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Right now, I get positive feedback from `validatePrivateKey` for the input values

* `e4ade2a5232a7c6f37e7b854a774e25e6047ee7c6d63e8304ae04fa190bc17` (31 bytes)
* `e4ade2a5232a7c6f37e7b854a774e25e6047ee7c6d63e8304ae04fa190bc1732aa` (33 bytes)

so it looks like in all the stack of validatePrivateKey, the input length is not checked.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by bitjson** [comment]
Hey @webmaster128, thanks for opening an issue!

Thanks, I should improve the documentation on `validatePrivateKey` to clarify the functionality there. There's [a short note here on it](https://github.com/bitjson/bitcoin-ts/blob/master/src/lib/crypto/secp256k1.ts#L75) – basically, I want to avoid adding any runtime checks which aren't necessary for 100% of consumers. 

For most applications, when a potential new key is generated, it should be 32 bytes in length, so also validating the length in `validatePrivateKey` would be extraneous.

Ideally, TypeScript will eventually support stronger type guarantees about the length of a typed array so our function signature can specifically require a 32-byte Uint8Array (https://github.com/Microsoft/TypeScript/issues/18471). This would never be an error at runtime, because the compiler should be able to catch any instance in which the programmer accidentally generated the wrong size key (or failed to validate the length of a user-provided key), and those errors should never make it to runtime.

**Comment by webmaster128** [comment]
:+1: makes sense, thanks
